[package]
name = "yashandb"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/yashan-technologies/yashandb-rust"
description = "An official Rust driver for YashanDB, providing a synchronous, blocking connection to a YashanDB instance."
keywords = ["yashandb", "database", "driver", "sql"]
categories = ["database", "database-implementations"]

[dependencies]
libloading = "0.8"
